version: '3'
services:

# Nginx Service
  nginx:
    image: nginx:1.20
    container_name: nginx_declara
    environment:
      - TZ=America/Mexico_City
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
